spring.application.name=task

#Configuração serve para deixa as fontes do terminal coloridas no vs code
spring.output.ansi.enabled=ALWAYS 

# Configurações de Banco de dados PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/task
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect